### ISSUE TITLE
Is this a clean room implementation or reusing any prior art?

### ISSUE THREAD

**Issue by xnox** [canonical/openssl-fips-java#42]
Note there was in the past attempts to port Tomcat native into OpenSSL bindings into JSSE https://github.com/wildfly-security/wildfly-openssl and although it has lots of things implemented, it is also very buggy and unstable.

And also appears to have stalled in development.

**Comment by pushkarnk** [comment]
Yes, this is a cleanroom implementation. It does not reuse code or design details from other projects.

JNI-based Java security providers, layered over a native security library are common in the Java security ecosystem. Thanks for letting me know about wildfly-openssl!

**Comment by xnox** [comment]
Nice!
